tabSize: 2
storybook: true
useIndexFile: false
generateComponentTests: false
generateContainerTests: false
modulesPath: src/modules
snakeCaseFileNames: false
templates:
  - name: 'storybook'
    text: |
      import React from 'react'
      import {storiesOf} from '@storybook/react'
      import {action} from '@storybook/addon-actions'
      import {withKnobs} from '@storybook/addon-knobs'
      import <%= componentName %> from '../<%= componentName %>'

      storiesOf('<%= moduleName %>', module)
        .addDecorator(withKnobs)
        .add('<%= componentName %>', () => (
          <<%= componentName %> />
        )
      )
  - name: 'container'
    text: |
      import {compose} from 'recompose'
      import {connect} from 'react-redux'
      import <%= componentName %> from '../components/<%= componentName %>'

      const mapStateToProps = state => ({

      })

      const mapDispatchToProps = {

      }

      const <%= componentName %>Container = compose(
        connect(
          mapStateToProps,
          mapDispatchToProps
        )
      )(<%= componentName %>)

      export default <%= componentName %>Container


  - name: 'component'
    text: |
      import React from 'react'
      import PropTypes from 'prop-types'
      import styled from 'styled-components'

      const <%= componentName %>Base = styled.div`

      `

      const <%= componentName %> = ({}) => (
        <<%= componentName %>Base>
          <%= componentName %>
        </<%= componentName %>Base>
      )

      <%= componentName %>.propTypes = {

      }

      export default <%= componentName %>
